name: Build & Deploy to Production
on:
  push:
    branches: [EB-Deploy2]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build file
        run: npm run build

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          source: dist/*
          target: ../var/www/staging-medschool.premed.pk/html/
          strip_components: 1
